const PDFDocument = require('pdfkit');

/**
 * Generate a PDF from the CapCut cutting guide text.
 *
 * The caller must pipe the returned doc BEFORE content is written,
 * so we accept an optional writable stream and pipe internally
 * to guarantee correct ordering (pipe before doc.end()).
 *
 * @param {string} cuttingGuide - The cutting guide text
 * @param {object} metadata - Video metadata
 * @param {import('stream').Writable} [outputStream] - Writable stream to pipe PDF into
 * @returns {PDFDocument}
 */
function generateGuidePDF(cuttingGuide, metadata = {}, outputStream) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    info: {
      Title: `CapCut Cutting Guide - ${metadata.videoType || 'Video'}`,
      Author: 'LK Digital Content Factory',
    },
  });

  // Pipe BEFORE writing any content so the stream receives all data
  if (outputStream) {
    doc.pipe(outputStream);
  }

  // Header
  doc.fontSize(20).font('Helvetica-Bold')
    .text('CapCut Pro Cutting Guide', { align: 'center' });
  doc.moveDown(0.5);

  doc.fontSize(10).font('Helvetica')
    .fillColor('#666666')
    .text(`Generated by LK Digital Content Factory`, { align: 'center' });

  if (metadata.videoType) {
    doc.text(`Video Type: ${metadata.videoType}`, { align: 'center' });
  }
  if (metadata.duration) {
    const mins = Math.floor(metadata.duration / 60);
    const secs = metadata.duration % 60;
    doc.text(`Duration: ${mins}:${String(secs).padStart(2, '0')}`, { align: 'center' });
  }

  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#CCCCCC');
  doc.moveDown(1);

  // Content - process the cutting guide line by line
  const lines = cuttingGuide.split('\n');
  doc.fillColor('#000000');

  for (const line of lines) {
    // Skip cut-data JSON block
    if (line.includes('<cut-data>')) break;

    const trimmed = line.trim();

    if (trimmed.startsWith('═')) {
      // Section separator
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#3B82F6');
      doc.moveDown(0.5);
    } else if (trimmed.match(/^📱|^🎯|^⚡|^⚠️/)) {
      // Section header
      doc.fontSize(14).font('Helvetica-Bold').text(trimmed);
      doc.moveDown(0.3);
    } else if (trimmed.match(/^📝|^🎨/)) {
      // Sub-header
      doc.fontSize(11).font('Helvetica-Bold').text(trimmed);
      doc.moveDown(0.2);
    } else if (trimmed.startsWith('✓')) {
      // Checklist item
      doc.fontSize(10).font('Helvetica').text(trimmed, { indent: 20 });
    } else if (trimmed.startsWith('•') || trimmed.startsWith('-')) {
      // Bullet point
      doc.fontSize(10).font('Helvetica').text(trimmed, { indent: 15 });
    } else if (trimmed.length > 0) {
      // Regular text
      doc.fontSize(10).font('Helvetica').text(trimmed);
    } else {
      doc.moveDown(0.3);
    }

    // Check for page break
    if (doc.y > 750) {
      doc.addPage();
    }
  }

  // Footer
  doc.moveDown(2);
  doc.fontSize(8).font('Helvetica').fillColor('#999999')
    .text('Generated by LK Digital Content Factory | AI-Powered CapCut Optimization', {
      align: 'center',
    });

  doc.end();
  return doc;
}

module.exports = { generateGuidePDF };
